import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  route("actor/:actorName", "routes/actor/$actorName.tsx"),
  route("actors", "routes/actors.tsx"),
  route("char/:charHanzi", "routes/char/$charHanzi.tsx"),
  route("chars", "routes/chars.tsx"),
  route("conflicts", "routes/conflicts.tsx"),
  route("invalid_data", "routes/invalid_data.tsx"),
  route("integrity", "routes/integrity.tsx"),
  route("phrase/:phraseHanzi", "routes/phrase/$phraseHanzi.tsx"),
  route("phrases", "routes/phrases.tsx"),
  route("phrases_import", "routes/phrases_import.tsx"),
  route("phrases_more", "routes/phrases_more.tsx"),
  route("phrases_process", "routes/phrases_process.tsx"),
  route("pinyin", "routes/pinyin.tsx"),
  route("place/:placeName", "routes/place/$placeName.tsx"),
  route("places", "routes/places.tsx"),
  route("practice", "routes/practice.tsx"),
  route("problematic", "routes/problematic.tsx"),
  route("prop/:propName", "routes/prop/$propName.tsx"),
  route("props", "routes/props.tsx"),
  route("settings", "routes/settings.tsx"),
  route("sibling_cards", "routes/sibling_cards.tsx"),
  route("similar_props", "routes/similar_props.tsx"),
  route("sound_components", "routes/sound_components.tsx"),
  route("stats", "routes/stats.tsx"),
  route("stats_progress", "routes/stats_progress.tsx"),
  route("story", "routes/story.tsx"),
  route("study", "routes/study.tsx"),
  route("study_weak_chars", "routes/study_weak_chars.tsx"),
  route("advance_cards", "routes/advance_cards.tsx"),
  route("sylable/:sylable", "routes/sylable/$sylable.tsx"),
  route("tag/:tagName", "routes/tag/$tagName.tsx"),
  route("tags", "routes/tags.tsx"),
  route("todo_chars", "routes/todo_chars.tsx"),
  route("chars_sentence_input", "routes/chars_sentence_input.tsx"),
  route(
    "chars_multiple_pronunciation",
    "routes/chars_multiple_pronunciation.tsx"
  ),
  route("exam_level", "routes/exam_level.tsx"),
  route("help", "routes/help.tsx"),
  route("homophones", "routes/homophones.tsx"),
  route("migration", "routes/migration.tsx"),
  route("tone/:toneName", "routes/tone/$toneName.tsx"),
  route("tones", "routes/tones.tsx"),
  route("zhuyin_typing", "routes/zhuyin_typing.tsx"),
  route("pronunciation", "routes/pronunciation.tsx"),
  route("dong_demo", "routes/dong_demo.tsx"),
  route("sound_eval", "routes/sound_eval.tsx"),
  // Handle development tool files
  route("installHook.js.map", "routes/dev_files.tsx"),
  index("routes/index.tsx"),
] satisfies RouteConfig;
